parameters:
#    parameter_name: value

services:
    library_platform.services.antispam:
        class: Library\PlatformBundle\Services\AntiSpam\AntiSpam
        arguments:
            - "@mailer"
            - "%locale%"
            - 100
    library_platform.services.email.application_mailer:
        class: Library\PlatformBundle\Services\Email\ApplicationMailer
        arguments:
            - "@mailer"
    # Créer un service d'envoi de mails générique (Pas de application, advert ...)
    library_platform.services.email.advert_mailer:
        class: Library\PlatformBundle\Services\Email\AdvertMailer
        arguments:
            - "@mailer"
    library_platform.services.doctrine_listener.application_creation:
        class: Library\PlatformBundle\Services\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@library_platform.services.email.application_mailer"
            - "@request_stack"
            - "%kernel.environment%"
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
    library_platform.services.doctrine_listener.advert:
        class: Library\PlatformBundle\Services\DoctrineListener\AdvertListener
        arguments:
            - "@library_platform.services.email.advert_mailer"
            - "@request_stack"
            - "%kernel.environment%"
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
            - { name: doctrine.event_listener, event: preRemove, method: preRemove }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
    # Service pour le TP3
    library_platform.services.purger.advert:
        class: Library\PlatformBundle\Services\Purger\Advert
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@monolog.logger"
