# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    tests_platform.antispam:
        # class : namespace où se trouve la classe
        class: Tests\PlatformBundle\AntiSpam\AntiSpam
        arguments:
            - "@mailer"
            - %locale%
            - 100
    tests_platform.email.application_mailer:
        class: Tests\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"
    tests_platform.doctrine_listener.application_creation:
        class: Tests\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@tests_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }