# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    tests_platform.antispam:
        # class : namespace où se trouve la classe
        class: Tests\PlatformBundle\AntiSpam\AntiSpam
        arguments:
            - "@mailer"
            - %locale%
            - 100
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    tests_platform.email.application_mailer
        class: Tests\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"