<?php

namespace Tests\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($limit)
    {
        $queryBuilder = $this->createQueryBuilder('app')
                        ->innerJoin('app.advert', 'a')
                        ->addSelect('a')
                        ->setMaxResults((int) $limit)
        ;

        return $queryBuilder
                ->getQuery()
                ->getResult()
        ;
    }
}
