<?php

namespace Tests\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($limit)
    {
        $queryBuilder = $this->createQueryBuilder('app')
                        ->innerJoin('app.advert', 'a')
                        ->addSelect('a')
                        ->setMaxResults((int) $limit)
        ;

        return $queryBuilder
                ->getQuery()
                ->getResult()
        ;
    }

    public function isFlood($ipAddress, $since = 15)
    {
        $date = new \DateTime();
        $date->sub(new \DateInterval('PT'.(int)$since.'S'));

        $queryBuilder = $this->createQueryBuilder('app')->where('app.date > :date');
        $queryBuilder->setParameter('date', $date);
        $queryBuilder->andWhere('app.ipAddress = :ip')->setParameter('ip', $ipAddress);

        return $queryBuilder
        ->getQuery()
        ->getResult()
        ;
    }
}
